name: Sync to Upstream

on:
  schedule:
    - cron: "0 04 * * *"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-20.04
    name: Sync HEAD with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout HEAD
        uses: actions/checkout@v3
        with:
          ref: master

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          target_sync_branch: master
          # REQUIRED 'target_repo_token' exactly like this!
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: aquasecurity/trivy-action
